name: Bug report
description: Report a bug
body:
  - type: dropdown
    id: platform
    attributes:
      label: "Stremio Platform"
      description: "Select the Stremio Platform you are using"
      options:
        - Windows
        - Windows (Beta)
        - macOS
        - Linux
        - Linux (Beta)
        - Web
        - Android Mobile
        - Android Mobile Beta
        - Android TV
        - Samsung Native TV
        - LG Native TV
        - Sony TV Android
        - Philips TV Android
        - Meta Quest VR
        - Raspberry Pi v4 (RPI4)
        - Raspberry Pi v5 (RPI5)
        - Steam Deck
        - iOS / iPadOS / macOS Native Beta
        - tvOS Beta
    validations:
      required: true

  - type: textarea
    id: describe_bug
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue in detail..."
    validations:
      required: true

  - type: textarea
    id: to_reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what you expected to see instead..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Provide URLs or drag-and-drop images after creating the issue."

  - type: input
    id: app_version
    attributes:
      label: "App Version"
      description: "Open the app settings to find it or you OS app manager"
      placeholder: v0.0.0
    validations:
      required: true

  - type: input
    id: device_info
    attributes:
      label: "Device Info"
      description: "Open the OS settings app to find which model you have"
      placeholder: iPhone 6, Pixel 8, Desktop, ...
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: "OS Version"
      description: "Open the OS settings app to find it or in some case displayed in the app settings"
      placeholder: Windows 10, iOS 14.4, Tizen 5.0, ...
    validations:
      required: true

  - type: input
    id: browser_info
    attributes:
      label: "Browser Info"
      description: "Open the about section of your browser to find the version"
      placeholder: Chrome 142, Firefox 145, ...

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Paste any relevant logs here (optional)"
      render: shell

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Any additional information (optional)"
